[package]
name = "website"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui = "0.29.1"
egui_commonmark = "0.18.0"
log = "0.4.22"
serde = { version = "1.0.215", features = ["derive"] }
wasm-bindgen-futures = "0.4.45"
web-sys = "0.3.72"
